name: Run Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Run Tests
        run: docker compose up --exit-code-from api-tests
        continue-on-error: true
      - name: Copy Allure Results from Container
        if: always()
        run: |
          docker cp restful_booker_tests:/app/allure-results ./allure-results || true

      - name: Upload Allure Results
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/
          retention-days: 30
      - name: Publish Allure Report
        if: always()
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results
          gh_pages: main
          allure_history: allure-history